<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Statistics validated against R reference results (Issue #8).
 *
 * Fixtures: tests/fixtures/stats/data.csv and reference.csv, generated by
 * tests/fixtures/stats/reference.R (R >= 4.3, base packages). Tolerance:
 * 1e-9 relative to max(1, |reference|).
 *
 * @package    block_catquiz_statistics
 * @copyright  2026 Ralf Erlebach
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace block_catquiz_statistics\stats;

/**
 * Reference tests for descriptive, linear, logistic, nested and path models.
 *
 * @covers \block_catquiz_statistics\stats\descriptive
 * @covers \block_catquiz_statistics\stats\design
 * @covers \block_catquiz_statistics\stats\distribution
 * @covers \block_catquiz_statistics\stats\linear_regression
 * @covers \block_catquiz_statistics\stats\logistic_regression
 * @covers \block_catquiz_statistics\stats\matrix
 * @covers \block_catquiz_statistics\stats\model_sequence
 * @covers \block_catquiz_statistics\stats\path_model
 */
final class statistics_reference_test extends \basic_testcase {
    /** @var float Relative tolerance. */
    private const TOL = 1e-9;

    /** @var array Fixture rows. */
    private static array $rows = [];

    /** @var array Reference values from R. */
    private static array $ref = [];

    /**
     * Load fixtures once.
     *
     * @return void
     */
    public static function setUpBeforeClass(): void {
        parent::setUpBeforeClass();
        $dir = __DIR__ . '/../fixtures/stats/';
        $h = fopen($dir . 'data.csv', 'r');
        $head = fgetcsv($h, 0, ',', '"', '');
        while (($r = fgetcsv($h, 0, ',', '"', '')) !== false) {
            $row = array_combine($head, $r);
            foreach ($row as $k => $v) {
                $row[$k] = $v === '' ? null : ($k === 'grp' ? $v : (float) $v);
            }
            self::$rows[] = $row;
        }
        fclose($h);
        $h = fopen($dir . 'reference.csv', 'r');
        fgetcsv($h, 0, ',', '"', '');
        while (($r = fgetcsv($h, 0, ',', '"', '')) !== false) {
            self::$ref[$r[0]] = (float) $r[1];
        }
        fclose($h);
    }

    /**
     * Compare against a reference value.
     *
     * @param string $name Reference name.
     * @param float|int|null $actual Value.
     * @return void
     */
    private function ref(string $name, float|int|null $actual): void {
        $this->assertArrayHasKey($name, self::$ref, "Missing reference $name");
        $expected = self::$ref[$name];
        $this->assertEqualsWithDelta($expected, $actual, self::TOL * max(1.0, abs($expected)), $name);
    }

    /**
     * Distribution functions.
     *
     * @return void
     */
    public function test_distributions(): void {
        $this->ref('dist.pt.2.1.10', distribution::t_cdf(2.1, 10));
        $this->ref('dist.qt.0975.37', distribution::t_quantile(0.975, 37));
        $this->ref('dist.pnorm.m1.3', distribution::normal_cdf(-1.3));
        $this->assertEqualsWithDelta(1.959963984540054, distribution::normal_quantile(0.975), 1e-12);
    }

    /**
     * Descriptives incl. missing count, quantile type 7 and frequencies.
     *
     * @return void
     */
    public function test_descriptive(): void {
        $d = descriptive::numeric(array_column(self::$rows, 'y'));
        foreach (['n', 'missing', 'mean', 'sd', 'median', 'q1', 'q3', 'min', 'max'] as $k) {
            $this->ref('desc.' . $k, $d[$k]);
        }
        $this->assertEqualsWithDelta($d['q3'] - $d['q1'], $d['iqr'], 1e-12);
        $c = descriptive::categorical(array_column(self::$rows, 'grp'));
        foreach (['A', 'B', 'C'] as $level) {
            $this->ref('freq.' . $level, $c['frequencies'][$level]['n']);
        }
    }

    /**
     * Linear regression with a categorical predictor: B, SE, p, CI, R², adjusted R², AIC, BIC, residuals, Cook's D.
     *
     * @return void
     */
    public function test_linear_regression(): void {
        $d = design::build(self::$rows, 'y', ['x1', 'x2', 'grp'], ['grp']);
        $this->assertSame(['(Intercept)', 'x1', 'x2', 'grpB', 'grpC'], $d['names']);
        $fit = linear_regression::fit($d);
        foreach ($fit['coefficients'] as $term => $c) {
            foreach (['b', 'se', 'p', 'cilow', 'cihigh'] as $k) {
                $this->ref("lm.$term.$k", $c[$k]);
            }
        }
        foreach (['n', 'r2', 'adjr2', 'aic', 'bic'] as $k) {
            $this->ref('lm.' . $k, $fit[$k]);
        }
        $this->ref('lm.res.min', $fit['residuals']['min']);
        $this->ref('lm.res.median', $fit['residuals']['median']);
        $this->ref('lm.res.max', $fit['residuals']['max']);
        $this->ref('lm.cook.over', $fit['cookover']);
        $this->assertNull($fit['coefficients']['grpB']['beta'], 'No standardised beta for dummy columns.');
        $this->assertSame(80, $fit['ntotal']);
        $this->assertSame(5, $fit['excluded'], 'Complete-case N transparent.');
    }

    /**
     * Standardised coefficients and VIF.
     *
     * @return void
     */
    public function test_standardised_and_vif(): void {
        $fit = linear_regression::fit(design::build(self::$rows, 'y', ['x1', 'x2'], [], ['grp']));
        $this->ref('std.x1', $fit['coefficients']['x1']['beta']);
        $this->ref('std.x2', $fit['coefficients']['x2']['beta']);
        $this->ref('vif.x1', $fit['vif']['x1']);
    }

    /**
     * Logistic regression: B, SE, p, Wald CI, AIC, deviances, McFadden R²; odds ratios = exp(B).
     *
     * @return void
     */
    public function test_logistic_regression(): void {
        $fit = logistic_regression::fit(design::build(self::$rows, 'b', ['x1', 'x2']));
        foreach ($fit['coefficients'] as $term => $c) {
            foreach (['b', 'se', 'p', 'cilow', 'cihigh'] as $k) {
                $this->ref("glm.$term.$k", $c[$k]);
            }
            $this->assertEqualsWithDelta(exp($c['b']), $c['or'], 1e-12);
        }
        foreach (['n', 'aic', 'deviance', 'nulldeviance', 'mcfadden'] as $k) {
            $this->ref('glm.' . $k, $fit[$k]);
        }
        $this->assertTrue($fit['converged']);
        $this->assertSame([], $fit['warnings']);
    }

    /**
     * Nested models share one sample; ΔR² and F-change p agree with R's anova().
     *
     * @return void
     */
    public function test_nested_models(): void {
        $seq = model_sequence::fit(self::$rows, 'y', [['x1'], ['x1', 'x2']]);
        $this->assertSame($seq['models'][0]['fit']['n'], $seq['models'][1]['fit']['n']);
        $this->ref('nested.r2.1', $seq['models'][0]['fit']['r2']);
        $this->ref('nested.r2.2', $seq['models'][1]['fit']['r2']);
        $this->ref('nested.p', $seq['models'][1]['change']['p']);
        $this->expectException(\coding_exception::class);
        model_sequence::fit(self::$rows, 'y', [['x1'], ['x2']]);
    }

    /**
     * Path model: coefficients, R² per endogenous variable, indirect = a*b, total = c' + a*b = simple slope.
     *
     * @return void
     */
    public function test_path_model_and_effects(): void {
        $pm = path_model::fit(self::$rows, ['m' => ['x1'], 'y' => ['m', 'x1']]);
        $this->ref('path.n', $pm['n']);
        $this->ref('path.a', $pm['equations']['m']['paths']['x1']['b']);
        $this->ref('path.b', $pm['equations']['y']['paths']['m']['b']);
        $this->ref('path.cprime', $pm['equations']['y']['paths']['x1']['b']);
        $this->ref('path.r2.m', $pm['equations']['m']['r2']);
        $this->ref('path.r2.y', $pm['equations']['y']['r2']);
        $eff = $pm['effects']['x1->y'];
        $this->ref('path.indirect', $eff['indirect']);
        $this->ref('path.total', $eff['total']);
        $this->assertCount(1, $eff['routes']);
        $this->assertSame(['x1', 'm', 'y'], $eff['routes'][0]['path']);
    }

    /**
     * Bootstrap CIs are reproducible with a seed and change with another seed.
     *
     * @return void
     */
    public function test_bootstrap_seeded(): void {
        $eq = ['m' => ['x1'], 'y' => ['m', 'x1']];
        $a = path_model::fit(self::$rows, $eq, 200, 7)['effects']['x1->y'];
        $b = path_model::fit(self::$rows, $eq, 200, 7)['effects']['x1->y'];
        $c = path_model::fit(self::$rows, $eq, 200, 8)['effects']['x1->y'];
        $this->assertSame([$a['bootcilow'], $a['bootcihigh']], [$b['bootcilow'], $b['bootcihigh']]);
        $this->assertNotSame($a['bootcilow'], $c['bootcilow']);
        $this->assertLessThan($a['indirect'], $a['bootcilow']);
        $this->assertGreaterThan($a['indirect'], $a['bootcihigh']);
        $this->assertSame(200, $a['bootn']);
    }

    /**
     * Guard rails: small-N warning, cyclic models, singular designs, non-binary logistic outcome.
     *
     * @return void
     */
    public function test_guard_rails(): void {
        $small = path_model::fit(array_slice(self::$rows, 0, 30), ['m' => ['x1']]);
        $this->assertContains('smalln', $small['warnings']);

        $rows = array_map(static fn($r) => $r + ['x1copy' => $r['x1']], self::$rows);
        try {
            linear_regression::fit(design::build($rows, 'y', ['x1', 'x1copy']));
            $this->fail('Collinear design accepted.');
        } catch (singular_matrix_exception $e) {
            $this->assertSame('stats:error:singular', $e->errorcode);
        }
        try {
            logistic_regression::fit(design::build(self::$rows, 'y', ['x1']));
            $this->fail('Non-binary outcome accepted.');
        } catch (\moodle_exception $e) {
            $this->assertSame('stats:error:notbinary', $e->errorcode);
        }
        $this->expectException(\coding_exception::class);
        path_model::fit(self::$rows, ['m' => ['y'], 'y' => ['m']]);
    }
}
